# Generated by Django 5.0.6 on 2026-02-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name="Ім'я користувача")),
                ('photo', models.ImageField(upload_to='users/', verbose_name='Еталонне фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
