# Generated by Django 5.0.6 on 2026-02-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='2FA Secret'),
        ),
    ]
