# Generated by Django 5.0.6 on 2026-04-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0002_userprofile_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='embedding_photo_count',
            field=models.IntegerField(default=1, verbose_name='Кількість фото при реєстрації'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='face_embedding',
            field=models.JSONField(blank=True, null=True, verbose_name='Усереднений embedding обличчя'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_threshold',
            field=models.FloatField(blank=True, default=0.68, null=True, verbose_name='Персональний поріг верифікації'),
        ),
    ]
